# Generated by Django 3.2.7 on 2025-04-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_malpraticedetection_lecture_hall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturehall',
            name='building',
            field=models.CharField(choices=[('FET', 'FET BUILDING'), ('TECH', 'TECH Block'), ('TECH', 'TECH BUILDING')], max_length=50),
        ),
    ]
